# GitHub Project Board Configuration
# This file documents the project board structure for Bidflow development

name: "Bidflow Development Board"
description: "Track development progress for Lineage Builders Proposal System"

columns:
  - name: "Backlog"
    description: "Features and bugs identified but not yet prioritized"
  
  - name: "To Do"
    description: "Prioritized items ready for development"
  
  - name: "In Progress"
    description: "Currently being worked on"
  
  - name: "Review"
    description: "Code review and testing phase"
  
  - name: "Done"
    description: "Completed and deployed"

labels:
  - name: "high-priority"
    color: "d73a49"
    description: "High priority items"
  
  - name: "medium-priority" 
    color: "fbca04"
    description: "Medium priority items"
  
  - name: "low-priority"
    color: "0e8a16"
    description: "Low priority items"
  
  - name: "bug"
    color: "d73a49"
    description: "Something isn't working"
  
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  
  - name: "ai-feature"
    color: "7057ff"
    description: "AI-related features"
  
  - name: "export"
    color: "0075ca"
    description: "Export functionality"
  
  - name: "ui-ux"
    color: "f9d0c4"
    description: "User interface and experience"
  
  - name: "backend"
    color: "d4c5f9"
    description: "Backend/API work"
  
  - name: "frontend"
    color: "c5def5"
    description: "Frontend development"
