/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tflmcxuntcmypajxwveq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbG1jeHVudGNteXBhanh3dmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDc0MTAsImV4cCI6MjA2OTE4MzQxMH0.-IApiyBpXaj_iGIiWbFx-lWRHgB5GOAcJAMAJuU2MW0"